---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: fanout1
  namespace: rabbitmq-system
spec:
  name: fanout1
  vhost: "vhost1"
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbit1
