---
apiVersion: v1
kind: Secret
metadata:
  name: demo-user-secret
  namespace: rabbitmq-system
type: Opaque
stringData:
  username: demo
  password: demo
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: user-rabbit1
  namespace: rabbitmq-system
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbit1
  importCredentialsSecret:
    name: demo-user-secret

