---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: qq2
  namespace: rabbitmq-system
spec:
  name: qq2
  vhost: "vhost2"
  type: quorum
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbit1
