---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: fanout-upstream
  namespace: rabbitmq-system
spec:
  name: fanout
  vhost: "upstream"
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbit2
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: fanout-downstream
  namespace: rabbitmq-system
spec:
  name: fanout
  vhost: "downstream"
  type: fanout
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbit2
