---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-secret
  namespace: rabbitmq-system
type: Opaque
stringData:
  username: demo
  password: demo
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: user
  namespace: rabbitmq-system
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: rabbit2
  importCredentialsSecret:
    name: credentials-secret

